import Head from "next/head";
import { Inter } from "next/font/google";
import LoginForm, { LoginFormInputs } from "@/components/login";
import axios from "axios";
import { parse } from "cookie";
import Link from "next/link";
import { useMyContext } from "@/utils/store";

const inter = Inter({ subsets: ["latin"] });
export default function Home({ userData }: { userData: any }) {
  const { setUser, user } = useMyContext();
  console.log(userData);
  console.log("userrrr" , user);
  

  const onSubmit = async (data: LoginFormInputs) => {
    const { email, password } = data;
    await axios.post("api/auth/login", { email, password });
    setUser(userData);
    location.reload();
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LoginForm onSubmit={onSubmit} />
        <Link href="blogs">blogsssss</Link>
        {userData.userId}
        {userData.email}
      </main>
    </>
  );
}

export async function getServerSideProps({ req }: any) {
  try {
    const cookies = parse(req.headers.cookie || "");
    const apiUrl = process.env.NEXT_PUBLIC_API_DOMAIN;
    const response = await fetch(`${apiUrl}/api/middleware/authenticate`, {
      headers: {
        Cookie: `postit=${cookies.postit || ""}`,
      },
    });
    const data = await response.json();

    return {
      props: {
        userData: data || "",
      },
    };
  } catch (error) {
    console.error("Error fetching data:", error);
  }
}
