import Head from "next/head";
import { Box, Container, Heading, VStack, Text } from "@chakra-ui/react";
import { StoryHighlights } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Postit- Stay Curious.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <Container px={0} maxW="100%">
        <Box
          px={`5vw`}
          maxW="100%"
          bgImage="url('/HeroBg.svg')"
          bgPosition="center"
          bgRepeat="no-repeat"
          bgSize={"cover"}
          h={`75.5vh`}
          display={`flex`}
          alignItems={`center`}
        >
          <VStack alignItems={`start`} maxW={`542px`}>
            <Heading as="h1" size="4xl" noOfLines={1} p={0} m={0}>
              Stay Curious.
            </Heading>
            <Text fontSize={`2xl`} noOfLines={3}>
              Lorem ipsum dolor sit ameetur adipiscing elit. Coctetur egestas
              massa velit aliquam. Molestim bibendum hnt ipsum orci, platea
              aliquam id ut.
            </Text>
          </VStack>
        </Box>
        <StoryHighlights />
      </Container>
    </>
  );
}
