import { useSession } from "next-auth/react";
import Head from "next/head";
import LoginForm, { LoginFormInputs } from "@/components/login";
import Link from "next/link";
import { signIn, signOut } from "next-auth/react";
import { Button, Container } from "@chakra-ui/react";

// const inter = Harmattan({ subsets: ["latin"], weight: "400" });
export default function Home() {
  const { data: Session } = useSession();
  console.log(Session);

  const onSubmit = async (data: LoginFormInputs) => {
    const { email, password } = data;
    try {
      const res = await signIn("credentials", {
        email,
        password,
        redirect: false,
      });
      console.log("resss", res);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Postit- Stay Curious.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container px={`5vw`} pt="2vw" maxW="100%">
        <LoginForm onSubmit={onSubmit} />
        <Link href="blogs">blogsssss</Link> <br />
        <Button onClick={() => signOut()}>LOG OUT</Button>
      </Container>
    </>
  );
}
